import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './Navbar'
import Body from './Body'
import CompanyBody from './CompanyBody'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Financial Site Web Scraper',
  description: 'Generated by create next app',
}

export default function RootLayout() {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {/* <Body /> */}
        <CompanyBody />

      </body>
    </html>
  )
}
